/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NET.Spam.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Spam.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Spam.Model
{
    /// <summary>
    /// AI advanced spam detection request
    /// </summary>
    [DataContract(Name = "SpamDetectionAdvancedFormSubmissionRequest")]
    public partial class SpamDetectionAdvancedFormSubmissionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedFormSubmissionRequest" /> class.
        /// </summary>
        /// <param name="inputFormFields">Form fields and values that you received in your form submission.</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise.</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise.</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise.</param>
        public SpamDetectionAdvancedFormSubmissionRequest(List<SpamDetectionAdvancedFormField> inputFormFields = default(List<SpamDetectionAdvancedFormField>), bool allowUnsolicitedSales = default(bool), bool allowPromotionalContent = default(bool), bool allowPhishing = default(bool))
        {
            this.InputFormFields = inputFormFields;
            this.AllowUnsolicitedSales = allowUnsolicitedSales;
            this.AllowPromotionalContent = allowPromotionalContent;
            this.AllowPhishing = allowPhishing;
        }

        /// <summary>
        /// Form fields and values that you received in your form submission
        /// </summary>
        /// <value>Form fields and values that you received in your form submission</value>
        [DataMember(Name = "InputFormFields", EmitDefaultValue = false)]
        public List<SpamDetectionAdvancedFormField> InputFormFields { get; set; }

        /// <summary>
        /// True if unsolicited sales should be allowed, false otherwise
        /// </summary>
        /// <value>True if unsolicited sales should be allowed, false otherwise</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowUnsolicitedSales", EmitDefaultValue = true)]
        public bool AllowUnsolicitedSales { get; set; }

        /// <summary>
        /// True if promotional content should be allowed, false otherwise
        /// </summary>
        /// <value>True if promotional content should be allowed, false otherwise</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPromotionalContent", EmitDefaultValue = true)]
        public bool AllowPromotionalContent { get; set; }

        /// <summary>
        /// True if phishing should be allowed, false otherwise
        /// </summary>
        /// <value>True if phishing should be allowed, false otherwise</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPhishing", EmitDefaultValue = true)]
        public bool AllowPhishing { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedFormSubmissionRequest {\n");
            sb.Append("  InputFormFields: ").Append(InputFormFields).Append("\n");
            sb.Append("  AllowUnsolicitedSales: ").Append(AllowUnsolicitedSales).Append("\n");
            sb.Append("  AllowPromotionalContent: ").Append(AllowPromotionalContent).Append("\n");
            sb.Append("  AllowPhishing: ").Append(AllowPhishing).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
