/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NET.Spam.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Spam.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Spam.Model
{
    /// <summary>
    /// Form field submitted to run spam detection on
    /// </summary>
    [DataContract(Name = "SpamDetectionAdvancedFormField")]
    public partial class SpamDetectionAdvancedFormField : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedFormField" /> class.
        /// </summary>
        /// <param name="fieldTitle">Title of the field.</param>
        /// <param name="fieldValue">Value of the field.</param>
        public SpamDetectionAdvancedFormField(string fieldTitle = default(string), string fieldValue = default(string))
        {
            this.FieldTitle = fieldTitle;
            this.FieldValue = fieldValue;
        }

        /// <summary>
        /// Title of the field
        /// </summary>
        /// <value>Title of the field</value>
        /*
        <example>LeadCompanyName</example>
        */
        [DataMember(Name = "FieldTitle", EmitDefaultValue = false)]
        public string FieldTitle { get; set; }

        /// <summary>
        /// Value of the field
        /// </summary>
        /// <value>Value of the field</value>
        /*
        <example>Acme, Inc.</example>
        */
        [DataMember(Name = "FieldValue", EmitDefaultValue = false)]
        public string FieldValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedFormField {\n");
            sb.Append("  FieldTitle: ").Append(FieldTitle).Append("\n");
            sb.Append("  FieldValue: ").Append(FieldValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
