/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Cloudmersive.APIClient.NET.Spam.Client.FileParameter;
using OpenAPIDateConverter = Cloudmersive.APIClient.NET.Spam.Client.OpenAPIDateConverter;

namespace Cloudmersive.APIClient.NET.Spam.Model
{
    /// <summary>
    /// AI advanced spam detection request
    /// </summary>
    [DataContract(Name = "SpamDetectionAdvancedRequest")]
    public partial class SpamDetectionAdvancedRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionAdvancedRequest" /> class.
        /// </summary>
        /// <param name="inputString">Input text string to detect spam against.</param>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced..</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise.</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise.</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise.</param>
        /// <param name="customPolicyID">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud.</param>
        public SpamDetectionAdvancedRequest(string inputString = default(string), string model = default(string), bool allowUnsolicitedSales = default(bool), bool allowPromotionalContent = default(bool), bool allowPhishing = default(bool), string customPolicyID = default(string))
        {
            this.InputString = inputString;
            this.Model = model;
            this.AllowUnsolicitedSales = allowUnsolicitedSales;
            this.AllowPromotionalContent = allowPromotionalContent;
            this.AllowPhishing = allowPhishing;
            this.CustomPolicyID = customPolicyID;
        }

        /// <summary>
        /// Input text string to detect spam against
        /// </summary>
        /// <value>Input text string to detect spam against</value>
        /*
        <example>Buy bitcoin now!!!!</example>
        */
        [DataMember(Name = "InputString", EmitDefaultValue = false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.
        /// </summary>
        /// <value>Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced.</value>
        /*
        <example>Advanced</example>
        */
        [DataMember(Name = "Model", EmitDefaultValue = false)]
        public string Model { get; set; }

        /// <summary>
        /// True if unsolicited sales should be allowed, false otherwise
        /// </summary>
        /// <value>True if unsolicited sales should be allowed, false otherwise</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowUnsolicitedSales", EmitDefaultValue = true)]
        public bool AllowUnsolicitedSales { get; set; }

        /// <summary>
        /// True if promotional content should be allowed, false otherwise
        /// </summary>
        /// <value>True if promotional content should be allowed, false otherwise</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPromotionalContent", EmitDefaultValue = true)]
        public bool AllowPromotionalContent { get; set; }

        /// <summary>
        /// True if phishing should be allowed, false otherwise
        /// </summary>
        /// <value>True if phishing should be allowed, false otherwise</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "AllowPhishing", EmitDefaultValue = true)]
        public bool AllowPhishing { get; set; }

        /// <summary>
        /// Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
        /// </summary>
        /// <value>Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud</value>
        [DataMember(Name = "CustomPolicyID", EmitDefaultValue = false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SpamDetectionAdvancedRequest {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  AllowUnsolicitedSales: ").Append(AllowUnsolicitedSales).Append("\n");
            sb.Append("  AllowPromotionalContent: ").Append(AllowPromotionalContent).Append("\n");
            sb.Append("  AllowPhishing: ").Append(AllowPhishing).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
