/*
 * spamapi
 *
 * Easily and directly scan and block spam security threats in input.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Cloudmersive.APIClient.NET.Spam.Client;
using Cloudmersive.APIClient.NET.Spam.Model;

namespace Cloudmersive.APIClient.NET.Spam.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpamDetectionApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        SpamDetectionAdvancedResponse SpamDetectFileAdvancedPost(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter));

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        ApiResponse<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostWithHttpInfo(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter));
        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        SpamDetectionResponse SpamDetectFilePost(string model = default(string), FileParameter inputFile = default(FileParameter));

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        ApiResponse<SpamDetectionResponse> SpamDetectFilePostWithHttpInfo(string model = default(string), FileParameter inputFile = default(FileParameter));
        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionFormSubmissionAdvancedResponse</returns>
        SpamDetectionFormSubmissionAdvancedResponse SpamDetectFormSubmissionAdvancedPost(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest));

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionFormSubmissionAdvancedResponse</returns>
        ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostWithHttpInfo(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest));
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        SpamDetectionAdvancedResponse SpamDetectTextStringAdvancedPost(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest));

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        ApiResponse<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostWithHttpInfo(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest));
        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        SpamDetectionResponse SpamDetectTextStringPost(SpamDetectionRequest body = default(SpamDetectionRequest));

        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        ApiResponse<SpamDetectionResponse> SpamDetectTextStringPostWithHttpInfo(SpamDetectionRequest body = default(SpamDetectionRequest));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpamDetectionApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostAsync(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file.
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectFileAdvancedPostWithHttpInfoAsync(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectFilePostAsync(string model = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX)
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionResponse>> SpamDetectFilePostWithHttpInfoAsync(string model = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionFormSubmissionAdvancedResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostAsync(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission
        /// </summary>
        /// <remarks>
        /// Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionFormSubmissionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionFormSubmissionAdvancedResponse>> SpamDetectFormSubmissionAdvancedPostWithHttpInfoAsync(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostAsync(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectTextStringAdvancedPostWithHttpInfoAsync(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectTextStringPostAsync(SpamDetectionRequest body = default(SpamDetectionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Perform AI spam detection and classification against input text string
        /// </summary>
        /// <remarks>
        /// Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SpamDetectionResponse>> SpamDetectTextStringPostWithHttpInfoAsync(SpamDetectionRequest body = default(SpamDetectionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISpamDetectionApi : ISpamDetectionApiSync, ISpamDetectionApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SpamDetectionApi : IDisposable, ISpamDetectionApi
    {
        private Cloudmersive.APIClient.NET.Spam.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public SpamDetectionApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public SpamDetectionApi(string basePath)
        {
            this.Configuration = Cloudmersive.APIClient.NET.Spam.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.Spam.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.Spam.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.Spam.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public SpamDetectionApi(Cloudmersive.APIClient.NET.Spam.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Cloudmersive.APIClient.NET.Spam.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.Spam.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.Spam.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cloudmersive.APIClient.NET.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SpamDetectionApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SpamDetectionApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cloudmersive.APIClient.NET.Spam.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.Spam.Client.GlobalConfiguration.Instance,
                new Cloudmersive.APIClient.NET.Spam.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.Spam.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public SpamDetectionApi(HttpClient client, Cloudmersive.APIClient.NET.Spam.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Cloudmersive.APIClient.NET.Spam.Client.Configuration.MergeConfigurations(
                Cloudmersive.APIClient.NET.Spam.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Cloudmersive.APIClient.NET.Spam.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Cloudmersive.APIClient.NET.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpamDetectionApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public SpamDetectionApi(Cloudmersive.APIClient.NET.Spam.Client.ISynchronousClient client, Cloudmersive.APIClient.NET.Spam.Client.IAsynchronousClient asyncClient, Cloudmersive.APIClient.NET.Spam.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Cloudmersive.APIClient.NET.Spam.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Cloudmersive.APIClient.NET.Spam.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.Spam.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Cloudmersive.APIClient.NET.Spam.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NET.Spam.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NET.Spam.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        public SpamDetectionAdvancedResponse SpamDetectFileAdvancedPost(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = SpamDetectFileAdvancedPostWithHttpInfo(model, preprocessing, allowPhishing, allowUnsolicitedSales, allowPromotionalContent, customPolicyId, inputFile);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        public Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostWithHttpInfo(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter))
        {
            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (model != null)
            {
                localVarRequestOptions.HeaderParameters.Add("model", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(model)); // header parameter
            }
            if (preprocessing != null)
            {
                localVarRequestOptions.HeaderParameters.Add("preprocessing", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(preprocessing)); // header parameter
            }
            if (allowPhishing != null)
            {
                localVarRequestOptions.HeaderParameters.Add("allowPhishing", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(allowPhishing)); // header parameter
            }
            if (allowUnsolicitedSales != null)
            {
                localVarRequestOptions.HeaderParameters.Add("allowUnsolicitedSales", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(allowUnsolicitedSales)); // header parameter
            }
            if (allowPromotionalContent != null)
            {
                localVarRequestOptions.HeaderParameters.Add("allowPromotionalContent", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(allowPromotionalContent)); // header parameter
            }
            if (customPolicyId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("customPolicyId", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(customPolicyId)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("inputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SpamDetectionAdvancedResponse>("/spam/detect/file/advanced", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectFileAdvancedPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectFileAdvancedPostAsync(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = await SpamDetectFileAdvancedPostWithHttpInfoAsync(model, preprocessing, allowPhishing, allowUnsolicitedSales, allowPromotionalContent, customPolicyId, inputFile, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text file. Analyzes input content as well as embedded URLs with AI deep learning to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Optional: Specify which AI model to use.  Possible choices are Normal and Advanced.  Default is Advanced. (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="preprocessing">Optional: Specify which preprocessing to Use.  Possible choices are None, Compatability and Auto.  Default is Auto. (optional, default to &quot;Auto&quot;)</param>
        /// <param name="allowPhishing">True if phishing should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowUnsolicitedSales">True if unsolicited sales should be allowed, false otherwise (optional, default to false)</param>
        /// <param name="allowPromotionalContent">True if promotional content should be allowed, false otherwise (optional, default to true)</param>
        /// <param name="customPolicyId">Apply a Custom Policy for Spam Enforcement by providing the ID; to create a Custom Policy, navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud (optional)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectFileAdvancedPostWithHttpInfoAsync(string model = default(string), string preprocessing = default(string), bool? allowPhishing = default(bool?), bool? allowUnsolicitedSales = default(bool?), bool? allowPromotionalContent = default(bool?), string customPolicyId = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (model != null)
            {
                localVarRequestOptions.HeaderParameters.Add("model", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(model)); // header parameter
            }
            if (preprocessing != null)
            {
                localVarRequestOptions.HeaderParameters.Add("preprocessing", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(preprocessing)); // header parameter
            }
            if (allowPhishing != null)
            {
                localVarRequestOptions.HeaderParameters.Add("allowPhishing", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(allowPhishing)); // header parameter
            }
            if (allowUnsolicitedSales != null)
            {
                localVarRequestOptions.HeaderParameters.Add("allowUnsolicitedSales", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(allowUnsolicitedSales)); // header parameter
            }
            if (allowPromotionalContent != null)
            {
                localVarRequestOptions.HeaderParameters.Add("allowPromotionalContent", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(allowPromotionalContent)); // header parameter
            }
            if (customPolicyId != null)
            {
                localVarRequestOptions.HeaderParameters.Add("customPolicyId", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(customPolicyId)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("inputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SpamDetectionAdvancedResponse>("/spam/detect/file/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectFileAdvancedPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        public SpamDetectionResponse SpamDetectFilePost(string model = default(string), FileParameter inputFile = default(FileParameter))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse> localVarResponse = SpamDetectFilePostWithHttpInfo(model, inputFile);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        public Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse> SpamDetectFilePostWithHttpInfo(string model = default(string), FileParameter inputFile = default(FileParameter))
        {
            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (model != null)
            {
                localVarRequestOptions.HeaderParameters.Add("model", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(model)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("inputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SpamDetectionResponse>("/spam/detect/file", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectFilePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectFilePostAsync(string model = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse> localVarResponse = await SpamDetectFilePostWithHttpInfoAsync(model, inputFile, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI spam detection and classification on an input image or document (PDF or DOCX) Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.  Supported file formats include DOCX, PDF, XLSX, PPTX, EML, MSG, JPG, PNG and WEBP.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to &quot;Advanced&quot;)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse>> SpamDetectFilePostWithHttpInfoAsync(string model = default(string), FileParameter inputFile = default(FileParameter), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (model != null)
            {
                localVarRequestOptions.HeaderParameters.Add("model", Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.ParameterToString(model)); // header parameter
            }
            if (inputFile != null)
            {
                localVarRequestOptions.FileParameters.Add("inputFile", inputFile);
            }

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SpamDetectionResponse>("/spam/detect/file", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectFilePost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionFormSubmissionAdvancedResponse</returns>
        public SpamDetectionFormSubmissionAdvancedResponse SpamDetectFormSubmissionAdvancedPost(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> localVarResponse = SpamDetectFormSubmissionAdvancedPostWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionFormSubmissionAdvancedResponse</returns>
        public Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostWithHttpInfo(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest))
        {
            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SpamDetectionFormSubmissionAdvancedResponse>("/spam/detect/form-submission/advanced", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectFormSubmissionAdvancedPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionFormSubmissionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionFormSubmissionAdvancedResponse> SpamDetectFormSubmissionAdvancedPostAsync(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionFormSubmissionAdvancedResponse> localVarResponse = await SpamDetectFormSubmissionAdvancedPostWithHttpInfoAsync(body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against a form submission Analyzes form input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionFormSubmissionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionFormSubmissionAdvancedResponse>> SpamDetectFormSubmissionAdvancedPostWithHttpInfoAsync(SpamDetectionAdvancedFormSubmissionRequest body = default(SpamDetectionAdvancedFormSubmissionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SpamDetectionFormSubmissionAdvancedResponse>("/spam/detect/form-submission/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectFormSubmissionAdvancedPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionAdvancedResponse</returns>
        public SpamDetectionAdvancedResponse SpamDetectTextStringAdvancedPost(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = SpamDetectTextStringAdvancedPostWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionAdvancedResponse</returns>
        public Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostWithHttpInfo(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest))
        {
            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SpamDetectionAdvancedResponse>("/spam/detect/text-string/advanced", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectTextStringAdvancedPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionAdvancedResponse> SpamDetectTextStringAdvancedPostAsync(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse> localVarResponse = await SpamDetectTextStringAdvancedPostWithHttpInfoAsync(body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionAdvancedResponse>> SpamDetectTextStringAdvancedPostWithHttpInfoAsync(SpamDetectionAdvancedRequest body = default(SpamDetectionAdvancedRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SpamDetectionAdvancedResponse>("/spam/detect/text-string/advanced", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectTextStringAdvancedPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>SpamDetectionResponse</returns>
        public SpamDetectionResponse SpamDetectTextStringPost(SpamDetectionRequest body = default(SpamDetectionRequest))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse> localVarResponse = SpamDetectTextStringPostWithHttpInfo(body);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <returns>ApiResponse of SpamDetectionResponse</returns>
        public Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse> SpamDetectTextStringPostWithHttpInfo(SpamDetectionRequest body = default(SpamDetectionRequest))
        {
            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<SpamDetectionResponse>("/spam/detect/text-string", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectTextStringPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SpamDetectionResponse</returns>
        public async System.Threading.Tasks.Task<SpamDetectionResponse> SpamDetectTextStringPostAsync(SpamDetectionRequest body = default(SpamDetectionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse> localVarResponse = await SpamDetectTextStringPostWithHttpInfoAsync(body, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI spam detection and classification against input text string Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-75 API calls depending on model selected.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NET.Spam.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Spam detection request (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SpamDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<Cloudmersive.APIClient.NET.Spam.Client.ApiResponse<SpamDetectionResponse>> SpamDetectTextStringPostWithHttpInfoAsync(SpamDetectionRequest body = default(SpamDetectionRequest), System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Cloudmersive.APIClient.NET.Spam.Client.RequestOptions localVarRequestOptions = new Cloudmersive.APIClient.NET.Spam.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };


            var localVarContentType = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Cloudmersive.APIClient.NET.Spam.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = body;

            // authentication (Apikey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarRequestOptions.HeaderParameters.Add("Apikey", this.Configuration.GetApiKeyWithPrefix("Apikey"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<SpamDetectionResponse>("/spam/detect/text-string", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("SpamDetectTextStringPost", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
